# Generated by Django 4.2.3 on 2023-08-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_journal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='trade',
            name='instrument',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='trade',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='Buy', max_length=255),
        ),
    ]
